// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransactionDataAccessLayer;

#nullable disable

namespace TransactionDataAccessLayer.Migrations
{
    [DbContext(typeof(TransactionsDbContext))]
    [Migration("20230531120529_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Bill", b =>
                {
                    b.Property<int>("Value")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Value"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("Value");

                    b.ToTable("Bills");

                    b.HasData(
                        new
                        {
                            Value = 20,
                            Amount = 5
                        },
                        new
                        {
                            Value = 50,
                            Amount = 5
                        },
                        new
                        {
                            Value = 100,
                            Amount = 5
                        },
                        new
                        {
                            Value = 200,
                            Amount = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
